name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation (v1)
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: udovychenkoqa
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Snake Animation (v3)
      - uses: Platane/snk@v3
        with:
          # GitHub user name to read the contribution graph from (**required**)
          # Using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}

          # List of files to generate
          # One file per line. Each output can be customized with options as query string.
          #
          # Supported options:
          # - palette:     A preset of color, one of [github, github-dark, github-light]
          # - color_snake: Color of the snake
          # - color_dots:  Comma-separated list of dots color.
          #                The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
